- hosts: 47.56.86.153
  remote_user: root
  tasks:
    - name: copy file
      copy: src={{path}}/{{filename}} dest=/opt/hana
      register: result
    - command: echo "helloworld"
      when: result|changed 
